# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

[build]
target-dir = "build/rust"

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[term]
progress.when = 'never'

[target.aarch64-kernel]
rustflags = [ "-C", "linker=toolchain/aarch64/bin/aarch64-elf-ld" ]

[target.x64-kernel]
rustflags = [ "-C", "linker=toolchain/x64/bin/x86_64-elf-ld" ]

[target.'cfg(debug_assertions)']
rustflags = ["-C", "force-frame-pointers=y"]
